=== gufanyi/wdp/src/resource/lui.docs/layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://com.founer.xap/schema/lui"  xmlns="http://com.founer.xap/schema/lui" elementFormDefault="qualified">
  <xs:element name="UIPart">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="Splitter"/>
        <xs:element maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element ref="ViewPart"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="isFlow"  type="xs:boolean" default="false"/>
      <xs:attribute name="jquery" type="xs:string" default="0"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Splitter">
    <xs:complexType>
      <xs:sequence>        
        <xs:element ref="SplitterOne"/>
        <xs:element ref="SplitterTwo"/>
      </xs:sequence>
      <xs:attribute name="boundMode" use="required" type="xs:integer" default="1"/>
      <xs:attribute name="divideSize" use="required" type="xs:integer" default="210"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="isInverse" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="isInverseFlowPanel" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="isOneTouch" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="orientation" use="required" type="xs:NCName" default="h"/>
      <xs:attribute name="spliterWidth" use="required" type="xs:integer" default="4"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SplitterTwo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ShutterLayout"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ShutterLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ShutterItems"/>
      </xs:sequence>
      <xs:attribute name="currentItem" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ShutterItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ShutterItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ShutterItem">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="text" use="required" type="xs:NCName" default="显示的文字"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SplitterOne">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TabLayout"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TabLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TabItems"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="TabRight"/>
      </xs:sequence>
      <xs:attribute name="currentItem" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="oneTabHide"  type="xs:boolean" default="false"/>
      <xs:attribute name="isOneTabHide"  type="xs:boolean" default="false"/>
      <xs:attribute name="OuterTab" type="xs:boolean" default="true"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
      <xs:attribute name="height" type="xs:string" />
      <xs:attribute name="width" type="xs:string" />
      <xs:attribute name="tabType" type="xs:string" default="top"/>
      <xs:attribute name="itemWidth" type="xs:string" />
      <xs:attribute name="itemHeight" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="TabItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="TabItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TabItem">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="active" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="i18nName" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="showCloseIcon" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="text" use="required" type="xs:NCName" default="页签"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TabRight">
    <xs:complexType>
      <xs:choice>     
        <xs:group ref="persongroup"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CanvasLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Border"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CardLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TabLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ShutterLayout"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" defalut="main"/>
      <xs:attribute name="width" use="required" type="xs:integer" default="200"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowVLayout">
    <xs:complexType>
      <xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVPanel"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHPanel"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" type="xs:string" default="main"/>
      <xs:attribute name="isAutoFill"  type="xs:string" default="false"/>
      <xs:attribute name="autoFill"  type="xs:string" default="0"/>
      
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowVPanel">
    <xs:complexType>
      <xs:choice>
        <xs:group ref="persongroup"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CanvasLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Border"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CardLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TabLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ShutterLayout"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ViewPart"/>
      </xs:choice>
      <xs:attribute name="height" type="xs:string" />
      <xs:attribute name="topBorder" type="xs:string" />
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" type="xs:NCName" default="main"/>
      <xs:attribute name="rightBorder"  type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowHLayout">
    <xs:complexType>
      <xs:choice>
        <xs:element maxOccurs="unbounded" ref="FlowHPanel"/>
        <xs:element maxOccurs="unbounded" ref="FlowVPanel"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" type="xs:string" default="main"/>
      <xs:attribute name="isAutoFill"  type="xs:string" default="false"/>
      <xs:attribute name="autoFill"  type="xs:string" default="0"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowHPanel">
    <xs:complexType>  
      <xs:choice>
        <xs:group ref="persongroup"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CanvasLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Border"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CardLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TabLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ShutterLayout"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ViewPart"/>
      </xs:choice>  
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="width"  type="xs:string"/>
      <xs:attribute name="widgetId"  type="xs:string" default="main"/>
      <xs:attribute name="rightBorder"  type="xs:string" default="1px #a3a3a5 solid"/>
      <xs:attribute name="className"  type="xs:string" default="lefthpanel"/>
      <xs:attribute name="leftBorder"  type="xs:string" default="1px solid #D1DFE4"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Border">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="BorderPanel"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="isShowBottom" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="isShowLeft" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="isShowRight" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="isShowTop" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
      <xs:attribute name="width" use="required" type="xs:string" default="1"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BorderPanel">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CanvasLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="CanvasPanel"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="styleClassName" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CanvasPanel">
    <xs:complexType>
       <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CardLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="CardPanel"/>
      </xs:sequence>
      <xs:attribute name="currentItem" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CardPanel">
    <xs:complexType>
       <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:group name="persongroup">
    <xs:choice>
        <xs:element minOccurs="0" maxOccurs="1" ref="CheckBox"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="CheckBoxGroup"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ComboBox"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="TextField"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="IntegerText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="DecimalText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="PwdText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="TextArea"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Radio"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="RadioGroup"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="DateText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Reference"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Label"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Link"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Iframe"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Form"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Tree"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Button"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Grid"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="MenuBar"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ToolBar"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="HtmlContent"/>
    </xs:choice>
  </xs:group>
  <xs:element name="CheckBox">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CheckBoxGroup">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
    <xs:element name="ComboBox">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TextField">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
      <xs:attribute name="imgsrc"  type="xs:string" />
      <xs:attribute name="type"  type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="IntegerText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DecimalText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PwdText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>  
  <xs:element name="TextArea">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Radio">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="RadioGroup">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DateText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Reference">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Label">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Link">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Iframe">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Form">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
      <xs:attribute name="label_position"  type="xs:string" default=""/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tree">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Button">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
      <xs:attribute name="className"  type="xs:string" default="blue_button_div"/>
      <xs:attribute name="styleClassName"  type="xs:string" default="blue_button_div"/>
    </xs:complexType>
    
  </xs:element>
  <xs:element name="Grid">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>    
  </xs:element>
  <xs:element name="MenuBar">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>    
  </xs:element>
   <xs:element name="ToolBar">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HtmlContent">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="personattrgroup">
    <xs:attribute name="height" type="xs:string" default="100%"/>
    <xs:attribute name="id" use="required" type="xs:string" />
    <xs:attribute name="left" use="required" type="xs:integer" default="0"/>
    <xs:attribute name="position" use="required" type="carType" default="relative">
      <xs:simpleType name="carType">
          <xs:restriction base="xs:NCName">
            <xs:enumeration value="relative"/>
            <xs:enumeration value="absolute"/>
            <xs:enumeration value="static"/>
          </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="top" use="required" type="xs:integer" default="0"/>
    <xs:attribute name="widgetId" use="required" type="xs:NCName" />
    <xs:attribute name="width" use="required" type="xs:string" default="100%"/>
  </xs:attributeGroup>
  
  <xs:element name="ViewPart">
    <xs:complexType>
      <xs:attribute name="id" use="required"   type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gufanyi/wdp/src/person/lui/nodes/rightMenu/rightMenu.main.layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="main_um" jquery="0">
    <FlowVLayout id="flowvlayout6127" widgetId="main">
        <FlowVPanel cssStyle="background-color:#C8FFDB;" height="40" id="panelv06127" topPadding="10" widgetId="main">
            <FlowHLayout id="flowhlayout6717" isAutoFill="false" widgetId="main">
                <FlowHPanel id="panelh06717" leftPadding="59" widgetId="main">
                    <TextField height="28" id="strTxt_MenuCtrlId" imgsrc="" left="0" position="relative" top="0" type="text" widgetId="main" width="190">
                    </TextField>
                </FlowHPanel>
                <FlowHPanel id="panelh26717" widgetId="main">
                    <TextField height="28" id="strTxt_MenuCtrlName" imgsrc="" left="0" position="relative" top="0" type="text" widgetId="main" width="190">
                    </TextField>
                </FlowHPanel>
            </FlowHLayout>
        </FlowVPanel>
        <FlowVPanel id="panelv16127" widgetId="main">
            <FlowHLayout id="flowhlayout2929" isAutoFill="false" widgetId="main">
                <FlowHPanel bottomBorder="2px blue solid" id="panelh02929" rightBorder="1px blue solid" topBorder="1px blue solid" widgetId="main" width="270">
                    <FlowVLayout id="flowvlayout6677" widgetId="main">
                        <FlowVPanel height="120" id="panelv06677" widgetId="main">
                            <Form height="100%" id="frm_RightMenu" label_position="" left="0" position="relative" top="0" widgetId="main" width="100%">
                            </Form>
                        </FlowVPanel>
                        <FlowVPanel id="flowvpanel16223" rightPadding="20" widgetId="main">
                            <Button align="right" height="24" id="btn_AddMenuItem" left="0" position="relative" top="0" widgetId="main" width="64">
                            </Button>
                        </FlowVPanel>
                    </FlowVLayout>
                </FlowHPanel>
                <FlowHPanel bottomBorder="1px blue solid" id="panelh22929" topBorder="1px blue solid" widgetId="main">
                    <Tree height="100%" id="tree_RightMenu" left="0" position="relative" top="0" widgetId="main" width="100%">
                    </Tree>
                </FlowHPanel>
            </FlowHLayout>
        </FlowVPanel>
        <FlowVPanel height="50" id="panelv26127" widgetId="main">
            <FlowHLayout id="flowhlayout5098" isAutoFill="false" widgetId="main">
                <FlowHPanel id="panelh05098" rightPadding="20" topPadding="20" widgetId="main">
                    <Button align="right" height="24" id="btn_Save" left="0" position="relative" top="0" widgetId="main" width="64">
                    </Button>
                </FlowHPanel>
                <FlowHPanel id="panelh25098" topPadding="20" widgetId="main" width="100">
                    <Button height="24" id="btn_Cancle" left="0" position="relative" top="0" widgetId="main" width="64">
                    </Button>
                </FlowHPanel>
            </FlowHLayout>
        </FlowVPanel>
    </FlowVLayout>
</UIPart>

=== gufanyi/wdp/src/person/lui/nodes/commitrule/commitrule.main.layout.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="main_um" isFlow="false">
  <FlowVLayout id="flowvlayoxt2633">
  	   <FlowVPanel id="panelv3ssq2" height="200">
  	       <FlowVLayout id="flowvlayoudd33">
  	       	   <FlowVPanel id="panelvlls92" height="30">
					<MenuBar height="100%" id="menubar1" left="0" position="relative" top="0" width="100%"></MenuBar>
  	       	   </FlowVPanel>
  	       	   <FlowVPanel id="lnsv3ws92">
  	       	   		<Grid height="100%" id="subRule_grid1" left="0" position="relative" top="0" width="100%">
					</Grid>
  	       	   </FlowVPanel>
  	       </FlowVLayout>
	   </FlowVPanel>
	   
	   <FlowVPanel id="pawelvl692">
			<FlowVLayout id="fuwvlakjoudd33">
			   <FlowVPanel id="pakelv3wk92" height="40">
			   		<FlowHLayout id="flowhdjfl">
			   			<FlowHPanel id="flowganelww" width="82">
			   				<Label id="fLabel" width="80" top="15" left="2" textAlign=""></Label>
			   			</FlowHPanel>
			   			<FlowHPanel id="flowhffelww">
			   				<TextField height="24" id="fCombo" position="relative" top="15" left="0" type="text" width="140">
						    </TextField>
			   			</FlowHPanel>
			   			<FlowHPanel id="flowganelww" width="300">
			   			</FlowHPanel>
			   		</FlowHLayout>
			   </FlowVPanel>
  	       	   <FlowVPanel id="pakelkkws92" height="30">
					<MenuBar height="100%" id="menubar2" left="0" position="relative" top="4" width="100%"></MenuBar>
  	       	   </FlowVPanel>
  	       	   <FlowVPanel id="pancc3ws92">
  	       	   		<Grid height="100%" id="subRule_grid2" left="0" position="relative" top="0" width="100%">
					</Grid>
  	       	   </FlowVPanel>
  	       </FlowVLayout>
	   </FlowVPanel>
	   
	   <FlowVPanel id="pawesdk692" height="45">
	   		<FlowHLayout id="flokgjfl">
			   	<FlowHPanel id="kkjjhhelww">
			   		<Button height="24" id="btn_ok" left="180" position="" top="15" width="70">
					</Button>
			   	</FlowHPanel>
			   	<FlowHPanel id="flolpafffelww">
			   		<Button height="24" id="btn_cancel" left="0" position="" top="15" width="70">
					</Button>
			   	</FlowHPanel>
			</FlowHLayout>
	   </FlowVPanel>
  </FlowVLayout>
</UIPart>

=== gufanyi/wdp/src/person/lui/nodes/uistate/uistate.main.layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="main_um" isFlow="false" jquery="0">
    <FlowVLayout id="flowvlayout2722" widgetId="main">
        <FlowVPanel id="panelv12722" widgetId="main">
            <FlowHLayout id="flowhlayout5453" isAutoFill="false" widgetId="main">
                <FlowHPanel id="panelh05453" widgetId="main" width="150">
                    <Border bottomColor="" bottomWidth="1" className="" color="" id="border1132" isShowBottom="false" isShowLeft="true" isShowRight="true" isShowTop="true" leftColor="" leftWidth="1" rightColor="" rightWidth="1" styleClassName="" topColor="" topWidth="1" widgetId="main" width="100">
                        <BorderPanel id="bordertrue1132" widgetId="main">
                            <Tree height="100%" id="view_tree" left="0" position="relative" top="0" widgetId="main" width="100%">
                            </Tree>
                        </BorderPanel>
                    </Border>
                </FlowHPanel>
                <FlowHPanel id="panelh25453" widgetId="main">
                    <FlowVLayout id="flowvlayout9556" widgetId="main">
                        <FlowVPanel height="30" id="panelv19556" topPadding="15" widgetId="main">
                            <FlowHLayout id="flowhlayout8616" isAutoFill="false" widgetId="main">
                                <FlowHPanel id="panelh08616" widgetId="main">
                                </FlowHPanel>
                                <FlowHPanel id="panelh18616" widgetId="main">
                                    <Label cssStyle="" family="" height="28" id="label_ctrl" left="0" position="relative" size="12" style="" textAlign="left" top="0" widgetId="main" width="100%">
                                    </Label>
                                </FlowHPanel>
                                <FlowHPanel id="panelh28616" widgetId="main">
                                </FlowHPanel>
                            </FlowHLayout>
                        </FlowVPanel>
                        <FlowVPanel id="panelv29556" widgetId="main">
                            <Grid height="100%" id="ctrl_grid" left="0" position="relative" top="0" widgetId="main" width="100%">
                            </Grid>
                        </FlowVPanel>
                    </FlowVLayout>
                </FlowHPanel>
            </FlowHLayout>
        </FlowVPanel>
        <FlowVPanel height="40" id="panelv22722" widgetId="main">
            <Border bottomColor="" bottomWidth="1" className="" color="" id="border1908" isShowBottom="true" isShowLeft="true" isShowRight="true" isShowTop="true" leftColor="" leftWidth="1" rightColor="" rightWidth="1" styleClassName="" topColor="" topWidth="1" widgetId="main" width="100">
                <BorderPanel id="bordertrue1908" widgetId="main">
                    <FlowHLayout id="flowhlayout3640" isAutoFill="false" widgetId="main">
                        <FlowHPanel id="panelh03640" rightPadding="5" topPadding="5" widgetId="main">
                            <Button align="right" height="24" id="btn_confirm" left="0" position="relative" top="0" widgetId="main" width="64">
                            </Button>
                        </FlowHPanel>
                        <FlowHPanel id="panelh23640" leftPadding="5" topPadding="5" widgetId="main">
                            <Button height="24" id="btn_cancel" left="0" position="relative" top="0" widgetId="main" width="64">
                            </Button>
                        </FlowHPanel>
                    </FlowHLayout>
                </BorderPanel>
            </Border>
        </FlowVPanel>
    </FlowVLayout>
</UIPart>

=== gufanyi/wdp/src/person/lui/nodes/refcfg/refcfg.main.layout.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="main_um" isFlow="false">
  <FlowVLayout id="flowvlayout5169">
    <FlowVPanel id="panelv05169" height="30" />
    <FlowVPanel id="panelv15169">
      <FlowHLayout id="flowhlayout1436">
        <FlowHPanel id="panelh01436" width="40" />
        <FlowHPanel id="panelh11436" >
          <Form id="refcfgform" left="0" top="0" width="100%" height="100%" position="relative" />
        </FlowHPanel>
        <FlowHPanel id="panelh21436" width="40" />
      </FlowHLayout>
    </FlowVPanel>
    <FlowVPanel id="panelv25169" height="30">
      <FlowHLayout id="flowhlayout3486">
        <FlowHPanel id="panelh03486" width="450" />
        <FlowHPanel id="panelh13486" width="70">
          <Button  id="okBtn" left="0" position="relative" width="70" className="blue_button_div" />
        </FlowHPanel>
        <FlowHPanel id="panelh23486" width="60">
          <Button id="cancelBtn" left="10" position="relative" width="70" />
        </FlowHPanel>
      </FlowHLayout>
    </FlowVPanel>
  </FlowVLayout>
</UIPart>
