=== gufanyi/wdp/src/resource/lui.docs/layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://com.founer.xap/schema/lui"  xmlns="http://com.founer.xap/schema/lui" elementFormDefault="qualified">
  <xs:element name="UIPart">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="Splitter"/>
        <xs:element maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element ref="ViewPart"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="isFlow"  type="xs:boolean" default="false"/>
      <xs:attribute name="jquery" type="xs:string" default="0"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Splitter">
    <xs:complexType>
      <xs:sequence>        
        <xs:element ref="SplitterOne"/>
        <xs:element ref="SplitterTwo"/>
      </xs:sequence>
      <xs:attribute name="boundMode" use="required" type="xs:integer" default="1"/>
      <xs:attribute name="divideSize" use="required" type="xs:integer" default="210"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="isInverse" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="isInverseFlowPanel" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="isOneTouch" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="orientation" use="required" type="xs:NCName" default="h"/>
      <xs:attribute name="spliterWidth" use="required" type="xs:integer" default="4"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SplitterTwo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ShutterLayout"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ShutterLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ShutterItems"/>
      </xs:sequence>
      <xs:attribute name="currentItem" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ShutterItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ShutterItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ShutterItem">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="text" use="required" type="xs:NCName" default="显示的文字"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SplitterOne">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TabLayout"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TabLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TabItems"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="TabRight"/>
      </xs:sequence>
      <xs:attribute name="currentItem" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="oneTabHide"  type="xs:boolean" default="false"/>
      <xs:attribute name="isOneTabHide"  type="xs:boolean" default="false"/>
      <xs:attribute name="OuterTab" type="xs:boolean" default="true"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
      <xs:attribute name="height" type="xs:string" />
      <xs:attribute name="width" type="xs:string" />
      <xs:attribute name="tabType" type="xs:string" default="top"/>
      <xs:attribute name="itemWidth" type="xs:string" />
      <xs:attribute name="itemHeight" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="TabItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="TabItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TabItem">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="active" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="i18nName" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="showCloseIcon" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="text" use="required" type="xs:NCName" default="页签"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TabRight">
    <xs:complexType>
      <xs:choice>     
        <xs:group ref="persongroup"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CanvasLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Border"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CardLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TabLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ShutterLayout"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" defalut="main"/>
      <xs:attribute name="width" use="required" type="xs:integer" default="200"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowVLayout">
    <xs:complexType>
      <xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVPanel"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHPanel"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" type="xs:string" default="main"/>
      <xs:attribute name="isAutoFill"  type="xs:string" default="false"/>
      <xs:attribute name="autoFill"  type="xs:string" default="0"/>
      
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowVPanel">
    <xs:complexType>
      <xs:choice>
        <xs:group ref="persongroup"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CanvasLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Border"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CardLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TabLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ShutterLayout"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ViewPart"/>
      </xs:choice>
      <xs:attribute name="height" type="xs:string" />
      <xs:attribute name="topBorder" type="xs:string" />
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" type="xs:NCName" default="main"/>
      <xs:attribute name="rightBorder"  type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowHLayout">
    <xs:complexType>
      <xs:choice>
        <xs:element maxOccurs="unbounded" ref="FlowHPanel"/>
        <xs:element maxOccurs="unbounded" ref="FlowVPanel"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" type="xs:string" default="main"/>
      <xs:attribute name="isAutoFill"  type="xs:string" default="false"/>
      <xs:attribute name="autoFill"  type="xs:string" default="0"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FlowHPanel">
    <xs:complexType>  
      <xs:choice>
        <xs:group ref="persongroup"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowVLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="FlowHLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CanvasLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Border"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="CardLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TabLayout"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ShutterLayout"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ViewPart"/>
      </xs:choice>  
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="width"  type="xs:string"/>
      <xs:attribute name="widgetId"  type="xs:string" default="main"/>
      <xs:attribute name="rightBorder"  type="xs:string" default="1px #a3a3a5 solid"/>
      <xs:attribute name="className"  type="xs:string" default="lefthpanel"/>
      <xs:attribute name="leftBorder"  type="xs:string" default="1px solid #D1DFE4"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Border">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="BorderPanel"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="isShowBottom" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="isShowLeft" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="isShowRight" use="required" type="xs:boolean" default="true"/>
      <xs:attribute name="isShowTop" use="required" type="xs:boolean" default="false"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
      <xs:attribute name="width" use="required" type="xs:string" default="1"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BorderPanel">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CanvasLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="CanvasPanel"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="styleClassName" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CanvasPanel">
    <xs:complexType>
       <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CardLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="CardPanel"/>
      </xs:sequence>
      <xs:attribute name="currentItem" use="required" type="xs:integer" default="0"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CardPanel">
    <xs:complexType>
       <xs:sequence>
        <xs:group ref="persongroup"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="widgetId" use="required" type="xs:NCName" default="main"/>
    </xs:complexType>
  </xs:element>
  <xs:group name="persongroup">
    <xs:choice>
        <xs:element minOccurs="0" maxOccurs="1" ref="CheckBox"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="CheckBoxGroup"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ComboBox"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="TextField"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="IntegerText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="DecimalText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="PwdText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="TextArea"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Radio"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="RadioGroup"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="DateText"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Reference"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Label"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Link"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Iframe"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Form"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Tree"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Button"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="Grid"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="MenuBar"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="ToolBar"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="HtmlContent"/>
    </xs:choice>
  </xs:group>
  <xs:element name="CheckBox">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CheckBoxGroup">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
    <xs:element name="ComboBox">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TextField">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
      <xs:attribute name="imgsrc"  type="xs:string" />
      <xs:attribute name="type"  type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="IntegerText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DecimalText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PwdText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>  
  <xs:element name="TextArea">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Radio">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="RadioGroup">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DateText">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Reference">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Label">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Link">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Iframe">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Form">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
      <xs:attribute name="label_position"  type="xs:string" default=""/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tree">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Button">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
      <xs:attribute name="className"  type="xs:string" default="blue_button_div"/>
      <xs:attribute name="styleClassName"  type="xs:string" default="blue_button_div"/>
    </xs:complexType>
    
  </xs:element>
  <xs:element name="Grid">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>    
  </xs:element>
  <xs:element name="MenuBar">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>    
  </xs:element>
   <xs:element name="ToolBar">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HtmlContent">
    <xs:complexType>
      <xs:attributeGroup ref="personattrgroup"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="personattrgroup">
    <xs:attribute name="height" type="xs:string" default="100%"/>
    <xs:attribute name="id" use="required" type="xs:string" />
    <xs:attribute name="left" use="required" type="xs:integer" default="0"/>
    <xs:attribute name="position" use="required" type="carType" default="relative">
      <xs:simpleType name="carType">
          <xs:restriction base="xs:NCName">
            <xs:enumeration value="relative"/>
            <xs:enumeration value="absolute"/>
            <xs:enumeration value="static"/>
          </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="top" use="required" type="xs:integer" default="0"/>
    <xs:attribute name="widgetId" use="required" type="xs:NCName" />
    <xs:attribute name="width" use="required" type="xs:string" default="100%"/>
  </xs:attributeGroup>
  
  <xs:element name="ViewPart">
    <xs:complexType>
      <xs:attribute name="id" use="required"   type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gufanyi/wdp/src/person/lui/nodes/pa/pa.settings.layout.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="settings_um" isFlow="false">
	<FlowVLayout id="flowv1">
		<FlowVPanel id="ffvp2">
			<TabLayout currentItem="0" id="tab2" oneTabHide="false" itemWidth="55" fontSize="12">
				<TabItem i18nName="w_pa-000017" langDir="pa_nodes" id="item_set" text="属性">
					 <CardLayout currentItem="0" id="cardlayout7773">
	                   <CardPanel id="cardpanel07773" >
	                      <Form id="adhintform" left="0" top="0" width="" height="" position="" />
	                   </CardPanel>
	                   <CardPanel id="cardpanel17773">
	                      <Grid id="grid_chart_option" left="0" top="0" width="100%" height="100%" position="" />
	                   </CardPanel>
	                   <CardPanel id="cardpanel17774">
	                      <TextField height="24" id="dftwin" imgsrc="" left="0" position="relative" top="15" type="text" widgetId="settings" width="200">
                          </TextField>
	                   </CardPanel>
	                  </CardLayout>
				</TabItem>
				<TabItem i18nName="w_pa-000018" langDir="pa_nodes" id="item_event" text="事件">
					<Grid id="grid_event" left="0" top="0" width="100%" height="100%" position="" />
				</TabItem>
				<TabItem i18nName="w_pa-000019" langDir="pa_nodes" id="item_pipe" text="管道">
					<TabLayout currentItem="0" id="pipetag" oneTabHide="false" tabType="top" itemWidth="45" fontSize="12">
						<TabItems>
							<TabItem active="0" i18nName="" id="tabitem_pipein_setting" showCloseIcon="false" text="输入">
								<Grid height="100%" id="grid_pipein" left="0" position="relative" top="0" width="100%">
								</Grid>
							</TabItem>
							<TabItem active="0" i18nName="" id="tabitem_pipeout_setting" showCloseIcon="false" text="输出">
								<Grid height="100%" id="grid_pipeout" left="0" position="relative" top="0" width="100%">
								</Grid>
							</TabItem>
							<TabItem i18nName="w_pa-000dd8" langDir="pa_nodes" id="item_connector" text="连接器">
								<Grid height="100%" id="grid_connector" left="0" position="relative" top="0" width="100%" widgetId="settings">
								</Grid>
							</TabItem>
						</TabItems>
						<TabRight id="tabright_pipe_tool" width="100">
							<MenuBar height="100%" id="menubar_pipe" left="0" position="relative" top="0" width="100%" widgetId="settings">
							</MenuBar>
						</TabRight>
					</TabLayout>
				</TabItem>
				<TabItem i18nName="w_pa-0ss0dk8" langDir="pa_nodes" id="item_propset" text="参数">
					<FlowVLayout id="flowvlayjjut4621" widgetId="settings">
						<FlowVPanel height="25" id="phlv04621" widgetId="settings">
							<MenuBar height="100%" id="menubar_param" left="0" position="relative" top="0" widgetId="settings" width="100%">
            				</MenuBar>
						</FlowVPanel>
						<FlowVPanel id="panelvsssdd1" widgetId="settings">
        					<Grid height="100%" id="grid_param" left="0" position="relative" top="0" width="100%" widgetId="settings">
							</Grid>
						</FlowVPanel>
					</FlowVLayout>
				</TabItem>
			    <Events>
			    	<Event async="true" eventType="TabEvent" method="afterItemInit_initAppWin" eventName="afterItemInit" controller="xap.lui.psn.pamgr.PaAppDsListener" onserver="true">
					</Event>
			    </Events>
			</TabLayout>
		</FlowVPanel>
	</FlowVLayout>
</UIPart>

=== gufanyi/wdp/src/person/lui/nodes/pa/pa.connector.layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="connector_um" isFlow="false" jquery="0">
    <FlowVLayout id="flowvlayout0765" widgetId="connector">
        <FlowVPanel id="panelv14621" widgetId="connector">
            <TabLayout currentItem="0" id="tag0856" oneTabHide="false" tabType="top" widgetId="connector">
                <TabItems>
                    <TabItem active="0" i18nName="" id="UITabItem00856" showCloseIcon="false" text="连接器属性" widgetId="connector">
                        <Form height="100%" id="form_conn" label_position="" left="0" position="relative" top="0" widgetId="connector" width="100%">
                        </Form>
                    </TabItem>
                </TabItems>
            </TabLayout>
        </FlowVPanel>
        <FlowVPanel id="flowvpanel18576" widgetId="connector">
            <TabLayout currentItem="0" id="tag5194" oneTabHide="false" tabType="top" widgetId="connector">
                <TabItems>
                    <TabItem active="0" i18nName="" id="UITabItem05194" showCloseIcon="false" text="关系映射" widgetId="connector">
                        <Grid height="100%" id="grid_map" left="0" position="relative" top="0" widgetId="connector" width="100%">
                        </Grid>
                    </TabItem>
                </TabItems>
                <TabRight id="tabspace17614" widgetId="connector" width="200">
                    <MenuBar align="right" height="100%" id="connmenu" left="0" position="relative" top="0" widgetId="connector" width="100%">
                    </MenuBar>
                </TabRight>
            </TabLayout>
        </FlowVPanel>
        <FlowVPanel height="30" id="flowvpanel14502" widgetId="connector">
            <FlowHLayout id="flowhlayout9494" isAutoFill="false" widgetId="connector">
                <FlowHPanel id="panelh09494" rightPadding="5" widgetId="connector">
                    <Button align="right" height="24" id="btn_confirm" left="0" position="relative" top="0" widgetId="connector" width="64">
                    </Button>
                </FlowHPanel>
                <FlowHPanel id="panelh19494" leftPadding="5" widgetId="connector">
                    <Button height="24" id="btn_cancel" left="0" position="relative" top="0" widgetId="connector" width="64">
                    </Button>
                </FlowHPanel>
            </FlowHLayout>
        </FlowVPanel>
    </FlowVLayout>
</UIPart>

=== gufanyi/wdp/src/person/lui/nodes/pa/pa.data.layout.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="data_um" isFlow="false">
	<FlowVLayout id="flvlo01">
		<FlowVPanel id="ffvp02">
			<TabLayout currentItem="0" id="outlookbar1" itemWidth="55" fontSize="12">
				<TabItem id="item_ctrl" text="控件">
					<Tree id="ctrltree" widgetId="data" />
				</TabItem>
				<TabItem  id="item_entity" text="模型">
					<Tree id="entitytree" widgetId="data" />
				</TabItem>
				<TabItem id="item_curr" text="视图">
					<Tree id="currtree" widgetId="data"  width="190"/>
				</TabItem>
				<TabItem  id="item_wins" text="窗口">
					<Tree id="winstree" widgetId="data"  width="190"/>
				</TabItem>
			</TabLayout>
		</FlowVPanel>
	</FlowVLayout>
</UIPart>

=== gufanyi/wdp/src/person/lui/nodes/dscfg/dscfg.main.layout.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<UIPart xmlns="http://com.founer.xap/schema/lui"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.founer.xap/schema/lui http://com.founer.xap/schema/lui/layout.xsd" id="main_um" isFlow="false">
  <FlowVLayout id="flowvlayout2718">
    <FlowVPanel id="panelv02718" height="10" />
    <FlowVPanel id="panelv12718">
      <FlowHLayout id="flowhlayout3118">
        <FlowHPanel id="panelh03118" width="10" />
        <FlowHPanel id="panelh13118">
          <FlowVLayout id="flowvlayout0201">
            <FlowVPanel id="flowvlayout00201"  height="100">
              <Form id="dscfgform" left="0" top="0" width="100%" height="100%" position="relative" />
            </FlowVPanel>
            <FlowVPanel id="flowvlayout10201">
              <TabLayout currentItem="0" id="tag1637" oneTabHide="false" tabType="top">
                <TabItems>
                  <TabItem active="true"  id="UITabItem01635" showCloseIcon="false" text="元数据属性">
                    <Grid id="classgrid" left="0" top="0" width="100%" height="100%" position="relative" />
                  </TabItem>
                  <TabItem active="true"  id="UITabItem01636" showCloseIcon="false" text="自定义属性">
                    <Grid id="fieldgrid" left="0" top="0" width="100%" height="100%" position="relative" />
                  </TabItem>
                  <TabItem active="false"  id="UITabItem01637" showCloseIcon="false" text="数据集关联">
                    <Grid id="relationsgrid" left="0" top="0" width="100%" height="100%" position="relative" />
                  </TabItem>
                  <!--
                  <TabItem active="false"  id="UITabItem01638" showCloseIcon="false" text="扩展属性">
                    <Grid id="dsattrgrid" left="0" top="0" width="100%" height="100%" position="relative" />
                  </TabItem>
                  -->
                </TabItems>
                <TabRight>
                  <FlowHLayout id="flowhlayout17528">
                    <FlowHPanel id="flowh0001" width="200">
                      <MenuBar id="func_menu" left="0" position="" top="0" widgetId="main" width="100%" />
                    </FlowHPanel>
                  </FlowHLayout>
                </TabRight>
              </TabLayout>
            </FlowVPanel>
          </FlowVLayout>
        </FlowHPanel>
        <FlowHPanel id="panelh23118" width="10" />
      </FlowHLayout>
    </FlowVPanel>
    <FlowVPanel id="panelv22718" height="50">
      <FlowHLayout id="flowhlayout0735">
        <FlowHPanel id="panelh40735"/>
        <FlowHPanel id="panelh20735" width="70">
          <Button id="okBtn" left="0"  position="relative" top="15" width="70" className="blue_button_div" />
        </FlowHPanel>
        <FlowHPanel id="panelh30735" width="100">
          <Button  id="cacelBtn" left="10"  position="relative" top="15" width="70" />
        </FlowHPanel>
      </FlowHLayout>
    </FlowVPanel>
  </FlowVLayout>
</UIPart>
